version: "3.8"

services:
  # ======================
  # INFRASTRUCTURE
  # ======================
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  # ======================
  # SPRING BOOT MICROSERVICES
  # ======================
  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - postgres
      - mongodb
      - rabbitmq

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - config-server

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "9001:9001"
    depends_on:
      - eureka-server
      - config-server
      - postgres
      - keycloak

  activity-service:
    build: ./activity-service
    container_name: activity-service
    ports:
      - "9002:9002"
    depends_on:
      - eureka-server
      - config-server
      - mongodb
      - rabbitmq

  ai-service:
    build: ./ai-service
    container_name: ai-service
    ports:
      - "9003:9003"
    depends_on:
      - eureka-server
      - config-server
      - mongodb
      - rabbitmq

volumes:
  postgres_data:
  mongo_data:
